# Generated by Django 3.2.3 on 2022-11-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('actividad', models.CharField(max_length=500, verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('actividad', models.CharField(max_length=500, verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=10, verbose_name='Identificación')),
                ('nombres', models.CharField(max_length=250, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.cargo', verbose_name='Cargos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.departamento', verbose_name='Departamentos')),
            ],
        ),
    ]
