# Generated by Django 3.2.3 on 2022-11-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_rename_image_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=250, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=250, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='identificacion',
            field=models.CharField(max_length=10, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=250, verbose_name='Nombres'),
        ),
    ]
