# Generated by Django 3.2.3 on 2022-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_auto_20221108_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=250, verbose_name='Cargo'),
        ),
    ]
