# Generated by Django 3.2.3 on 2022-11-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0013_alter_empleado_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='activo',
        ),
    ]
