# Generated by Django 3.2.3 on 2022-11-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0018_alter_empleado_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.cargo', verbose_name='Cargo'),
        ),
    ]
